config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path=>'',
                              :path_name=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
                              :controllers=>{:registrations=>'registrations'},:confirmations => 'confirmations'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#home"

  resources :users, only: [:show]

  resources :rooms do
    resources :reservations, only: [:create]
    resources :reviews, only: [:create, :destroy]
  end

  resources :photos

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get '/search' => 'pages#search'

end

app/views/layouts/_navigation.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Airbbbnb', root_path, {:class=>"navbar-brand"} %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_room_path do %>
              <i class="fa fa-home fa-lg"></i> Devenez hôte
          <% end %>
        </li>
        <% if (!user_signed_in?) %>
          <li><%= link_to 'Inscription', new_user_registration_path %></li>
          <li><%= link_to 'Identification', new_user_session_path %></li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to conversations_path do %>Messages<% end %></li>
            <li><%= link_to 'Mes voyages', root_path %></li>
            <li><%= link_to 'Modifier mon profil', edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbbbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= render 'shared/message' %>
    <div class="container"> <%= yield %> </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>